---
- name: Update .profile with ANSIBLE_CONFIG
  lineinfile:
    dest: "/home/{{ default_user.dev.user }}/.profile"
    line: 'export ANSIBLE_CONFIG=/home/{{ default_user.dev.user }}/{{ ansible_dir[use_ansible] }}/config/ansible.cfg'
    insertafter: "EOF"
    regexp: '^export ANSIBLE_CONFIG=' 
    state: present
  become: yes
  when:
    - do_ansible is defined
    - do_ansible