---
- name: Generiere Config-Files
  template:
    src: "sensible_data/{{ item }}.j2"
    dest: "/home/{{ default_user.dev.user }}/data/sensibleData/{{ item }}"
    mode: '0600'
    owner: "{{ default_user.dev.user }}"
    group: "{{ default_user.dev.group }}"
  become: yes
  with_items:
    - "path.json"
    - "router.json"
    - "privateEnv.json"
    - "workEnv.json"