---
- name: Install Python PIP
  apt:
    name: [ "python", "python3", "python-pip", "python3-pip" ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes
