---
- name: Register Keys for Debian Buster
  apt_key:
    url: "{{ item }}"
    state: present
  become: yes
  ignore_errors: yes
  with_items:
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
  when: 
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"

- name: Add kubernetes repository for Debian Buster
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes
  with_items:
    - deb https://apt.kubernetes.io/ kubernetes-xenial main
  when: 
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"

- name: Install kubernetes Packages
  apt:
    name: [ 'kubectl' ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes